#+title: A Response to Bradbury's 'There Will Come Soft Rains'
#+date: 2021-01-27 14:22:41
#+layout: single
#+type: post
#+draft: false
#+summary: My personal thoughts on Ray Bradbury's 'There Will Come Soft Rains'.
#+tags[]: dgst101

I personally feel like /'There Will Come Soft Rains'/ focuses on how technology is a danger to people and really on the negative aspects as a whole, rather than any of the positive aspects that technology provides people. To me, it sort of comes across as a "technology bad" sort of tone, which kind of seems condescending (at least, it does in my opinion).

I am a cybersecurity minor, so I definitely understand how technology and poorly implemented tools/APIs make life much more secure. (On a side note - some political stuff ahead. Not any real opinions, but consider this a heads-up.) As an example, before Parler was brought offline after the events from the 6th, security researchers were able to gather over 30TB of data due to a poorly implemented API[fn:1].





* References
[fn:1] https://www.usatoday.com/story/tech/news/2021/01/11/parler-hack-platform-archived-hackers-capitol-riots/6629772002/