#+title: The New Internet (Final Project)
#+date: 2021-04-24T15:45:25-04:00
#+layout: single
#+type: post
#+draft: false
#+dgstArchive: false
#+dgstLink: 
#+featured:
#+slug: the-new-internet
#+tags[]: dgst101
#+categories[]: dgst101 webdev

Personally, I really had no idea where to start with regards to the final
project simply because the prompt was so vague. I decided to set up a
[[https://jhilker.gitlab.io/the-new-internet/][website]] with ways the average user could improve their time on the internet. However, so much of it comes down to government breaking up monopolies and forcing harsher punishmments on companies, as well as protecting people's data that it's hard to really improve the internet when it would effectively require a re-write from the ground up to protect both a user's data and their privacy. 

Like I said on that website, I wanted to focus on 3 major issues with the internet - monopolies, privacy (or rather, the lack of it), and finally, misinformation. In addition, I wanted to cover one minor issue I have with the internet (and web development/design generally) - the lack of dark mode on many websites. It's 2021, there's not an excuse to not have one. 

Overall, I don't feel super satisfied with the project I turned out - although I wanted to do more with the project, there were other, larger projects I had to do where the some of the other people in group didn't do their fair share, so I along with one or two other people had to pick up their slack. 

