#+title: What Is The Internet?
#+date: 2021-02-14 21:45:41
#+layout: single
#+type: post
#+thumbnail: https://images.unsplash.com/photo-1580323434723-3edb667414a5?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80
#+draft: false
#+summary: My personal thoughts on the Internet, and what exactly it is.
#+categories[]: dgst101
#+tags[]: dgst101

The Internet, to me at least, is so many different things that it's difficult to nail down what /exactly/ it is. While obviously there's the technical definition of what it is, I've had so much experience using the internet and interacting with people on it that it's really difficult to pin down what exactly it is.

Some of my favorite memories have happened because of the internet - like playing first raid in /Destiny/ (the Vault of Glass) and getting my first Exotic, the Hard Light, as well as more physical events such as being able to build my PC with the parts I ordered on Amazon.

Obviously, not every experience I've had on the internet is a good thing. I've found out bad news multiple times through the internet, some of which can relate to my /Destiny/ clan. I don't want to get too personal, so I'll leave it at that. I also feel like online classes have overall been more of a negative. For one thing, I find it easier to get distracted during a Zoom call. I also find online classes to be a negative, especially for this semester, considering this is my final semester and I would have liked to have been able to spend it on campus with my friends. And at the same time, so many companies are gathering so much information on you that any sort of privacy you might have once had has essentially been tossed out the window, all in the name of engagement and profits. 

Overall, I'm not really sure how to define the internet, just because my experiences have been so varied. I realize it seems like a cop out answer - I'm just really unsure of how to define it, because everyone's experiences have been so drastically varied with it that everyone could have a different definition for it. The easiest way to define it might be to consider the contrasts for various aspects of the internet, as unsatisfying as that may be.