baseURL = "https://jhilker.com"
languageCode = "en-us"
pygmentsCodeFences = true
pygmentsUseClasses = true
theme = "all-for-one"
title = "Jacob's Website"
linenos = true
pygmentsOptions = "linenos=table"
disqusShortname = "jhilker"
paginate = 5

[params]
title = "Jacob's Website"
author = "Jacob Hilker"
customCss = ["css/custom.css"]
description = "I am a Python dev and a fan of Hugo. Currently looking for work."
themePref = "dark"
keywords = ""
profilePic = "pics/jhilker.jpg"
commentsrc = "utterances"
mainSections=['post']
enableToc = false
portfolio_paginate = 2

[params.math]
enable = true
use = "katex"

[params.utterances]
repo = "jhilker1/website-comments"
theme = "preferred-color-scheme"
issueMap = "pathname"


[outputFormats.RSS]
baseName = "feed"
mediatype = "application/rss"


[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "resume"
name = "Resumé"
url = "/resume/"
weight = 3

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 4

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 5

[[menu.main]]
identifier = "recents"
name = "Recent Posts"
url = "/blog/"
parent = "blog"
weight = 1

[[menu.main]]
identifier = "archive"
name = "Blog Archive"
url = "/archive/"
parent = "blog"
weight = 2

[[menu.main]]
identifier = "feed"
name = "RSS Feed"
url = "/blog/feed.xml"
parent = "blog"
weight = 3

[[menu.main]]
identifier = "config"
name = "Configs"
url = "https://config.jhilker.com"
weight = 6

[[menu.main]]
identifier = "source"
name = "Source"
url = "https://gitlab.com/jhilker/jhilker.gitlab.io"
weight = 7

[[params.socials]]
icon = "fab fa-gitlab"
title = "GitLab"
url = "https://gitlab.com/jhilker"

[[params.socials]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/jhilker1"

[[params.socials]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/jhilker"

[[params.socials]]
icon = "fab fa-dev"
title = "Dev.to"
url = "https://dev.to/jhilker"

[[params.socials]]
icon = "fab fa-codepen"
title = "CodePen"
url = "https://codepen.io/hilkerj"

[[params.socials]]
icon = "fas fa-rss"
title = "RSS Feed"
url = "/blog/feed.xml"

[[params.socials]]
icon = "fas fa-envelope"
title = "Home"
url = "mailto:jacob.hilker2@gmail.com"

[permalinks]
blog = "/:section/:year/:month/:slug/"

[markup.goldmark.renderer]
unsafe= true
[related]
  includeNewer= true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "categories"
    weight = 80

  [[related.indices]]
    name = "tags"
    weight = 80


  [[related.indices]]
    name = "series"
    weight = 80


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
