baseURL = "/"
languageCode = "en-us"
pygmentsCodeFences = true
pygmentsUseClasses = true
theme = "anatole"
#theme = "m10c"
title = "Jacob's Website"
linenos = true
pygmentsOptions = "linenos=table"
disqusShortname = "jhilker"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "resume"
name = "Resumé"
url = "/resume/"
weight = 3

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 4

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 5

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/blog/archive/"
weight = 6

[[menu.main]]
identifier = "DGST101"
name = "Digital Studies"
url = "/dgst101/"
weight = 7

#[[menu.main]]
#identifier = "dgstarchive"
#name = "DGST101 Archive"
#url = "/dgst101/archive/"
#weight = 8 

[[menu.main]]
identifier = "dgst101feed"
name = "DGST101 Feed"
url = "/dgst101/feed.xml"
weight = 8

[[menu.main]]
identifier = "gitlab"
name = "Source"
url = "https://gitlab.com/jhilker/jhilker.gitlab.io"
weight = 9

[outputFormats.RSS]
baseName = "feed"
mediatype = "application/rss"

[params]
author = "Jacob Hilker"
customCss = ["css/custom.css", "css/syntax.css"]
description = "This is a website."
displayMode = "dark"
keywords = ""
mainSections = ["blog", "project"]
profilePicture = "pics/jhilker.jpg"
title = "Jacob's Website"
[params.blog]
commentSrc = "graphcomment"
## M10C
#avatar = "pics/jhilker.jpg"
## M10C Nord Config
#[params.style]
#  darkestColor = "#2e3440"
#  darkColor = "#3b4252"
#  lightColor = "#d8dee9"
#  lightestColor = "#eceff4"
#  primaryColor = "#b16286"

[params.math]
enable = true
use = "katex"
[[params.socialIcons]]
icon = "fab fa-gitlab"
title = "GitLab"
url = "https://gitlab.com/jhilker"
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/jhilker1"
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/jhilker"
[[params.socialIcons]]
icon = "fab fa-dev"
title = "Dev.to"
url = "https://dev.to/jhilker"
[[params.socialIcons]]
icon = "fab fa-codepen"
title = "CodePen"
url = "https://codepen.io/hilkerj"
[[params.socialIcons]]
icon = "fas fa-rss"
title = "RSS Feed"
url = "/blog/feed.xml"
[[params.socialIcons]]
icon = "fas fa-envelope"
title = "Home"
url = "mailto:jacob.hilker2@gmail.com"

[permalinks]
#blog = "/:section/:year/:month/:day/:slug/"
#dgst101 = "/blog/:section/:year/:month/:day/:slug/"
blog = "/:section/post/:year/:month/:slug/"
dgst101 = "/blog/:section/:year/:month/:slug/"
page = "/:slug/"
archive = "/blog/:section"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"