baseURL = "https://jhilker.gitlab.io"
languageCode = "en-us"
pygmentsCodeFences = true
pygmentsUseClasses = true
theme = "anatole"
title = "Jacob's Website"
linenos = true
pygmentsOptions = "linenos=table"
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "resume"
name = "Resumé"
url = "/resume/"
weight = 2

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 3

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 4

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 5
[outputFormats.RSS]
baseName = "feed"
mediatype = "application/rss"

[params]
author = "Jacob Hilker"
customCss = ["css/custom.css", "css/syntax.css"]
description = "This is a website."
displayMode = "dark"
keywords = ""
mainSections = ["blog", "project"]
profilePicture = "pics/jhilker.jpg"
title = "Jacob's Website"

[params.math]
enable = true
use = "katex"
[[params.socialIcons]]
icon = "fab fa-gitlab"
title = "GitLab"
url = "https://gitlab.com/jhilker"
[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/jhilker1"
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/jhilker"
[[params.socialIcons]]
icon = "fab fa-dev"
title = "Dev.to"
url = "https://dev.to/jhilker"
[[params.socialIcons]]
icon = "fab fa-codepen"
title = "CodePen"
url = "https://codepen.io/hilkerj"
[[params.socialIcons]]
icon = "fas fa-rss"
title = "RSS Feed"
url = "/blog/feed.xml"
[[params.socialIcons]]
icon = "fas fa-envelope"
title = "Home"
url = "mailto:jacob.hilker2@gmail.com"

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"
page = "/:slug/"
archive = "/blog/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"
