#+title: Developing a Hugo Theme
#+date: 2021-03-31T22:41:42-04:00
#+layout: single
#+type: post
#+draft: true
#+dgstArchive: false
#+dgstLink: 
#+featured: true
#+slug: develop-first-hugo-theme
#+series: Developing A Hugo Theme
#+series_weight: 1
#+tags[]: hugo html css javascript js webdev 
#+categories[]: Hugo webdev Programming


Although I truly love the [[https://github.com/lxndrblz/anatole][Anatole]] theme for Hugo, I found that while it was good for my blog, it wasn't as good for all of my use cases - primarily my resume, since I felt like the sidebar was too big and took away from the actual content of the resume, along with several other minor issues.[fn:1]  That being said, it is an excellent theme, and there were many things I liked about it when I was using it that I wanted to incorporate into my own theme, even with the modifications to layouts I had made over time to it.

    - Dark mode. It really should just be available on every site in 2021 without having to use a browser extension like [[https://github.com/darkreader/darkreader][Dark Reader]]. Even if a user doesn't want dark mode, at least having the option available is nice.
    - The clean aesthetic. I'm not totally sure how to explain it, but just the layout of the Anatole theme is very clean, and I really liked that.
    - Customizability. I love having the ability to tweak the theme to look exactly how I want to make it look. In addition, adding interactivity like a dashboard for my projects is incredibly helpful with custom javascript.

With that in mind, I started looking into a framework I could use that could cover my requirements while still being relatively lightweight, and I finally came upon [[https://www.gethalfmoon.com][Halfmoon CSS]], an alternative to Bootstrap that came with a dark mode out of the box.

* How I Got Started
Beyond just reading the documentation, I decided to play around with the version of Halfmoon hosted on a CDN just to try it out.

[fn:1] While I could just use CSS for many of the things I talk about here, I wanted to work on a project I could add to my portfolio.