#+title: Using a Makefile With My Website
#+date: 2021-03-02T20:41:53-05:00
#+layout: single
#+type: post
#+draft: true
#+dgstArchive: false
#+dgstLink: 
#+featured: false
#+slug: using-makefiles-with-hugo
#+categories[]: Hugo
#+tags[]: Makefile software hugo emacs orgmode org_mode

It shouldn't be a surprise that I use Hugo as a static site generator. Not only is it fast, but it is also incredibly customizable, which is something that I find useful considering my website has so much stuff on it. In addition, being able to create shortcodes to avoid reusing code on certain pages is such a helpful tool for wikis. Finally, having support for Emacs' [[https://orgmode.org/][Org-Mode]] is what initially drew me to Hugo in the first place. I had tried using org-publish to try and set up a website, but had so many little issues with it that I decided to scrap it and keep looking around for a better way to set up a website. That was when I found Hugo, and decided to try it out. 


Ultimately, I found that when I was starting to create layouts and templates, typing the full =hugo server -D --navigateToChanged= was just long to type (yes, lazy, I know), especially when I was debugging an error with my shortcodes and templates. Being able just to type =make server= makes it much faster for me to debug code but also to get previews of code. 

* Not Just For Debugging
Hugo also allows for content to be created with a certain [[https://gohugo.io/content-management/archetypes/][archetype]] - by default, this matches the directory you are creating the content for. As an example, if I had an archetype called =blog.org=, if I ran =hugo new blog/hello-world.org= the file =content/blog/hello-world.org= would be created, with all the content needed for a blog post. As an example, here's what my org-mode project archetype looks like:

#+begin_example
#+title: 
#+draft: true
#+srclang: 
#+srcicon: 
#+summary: 
#+type: project
#+featured: 
#+layout: single
#+percDone: 0
#+lastUpdated: 
#+docs:
#+site:
#+gitlab:
#+github:
#+end_example

