#+title: My First Hackathon
#+date: 2021-03-12T17:08:55-05:00
#+layout: single
#+type: post
#+draft: true
#+dgstArchive: false
#+dgstLink: 
#+featured: false
#+slug:
#+tags[]: hackathon software
#+categories[]: Software 

New States may be employed in the Service of the Union, suppress Insurrections and repel Invasions. New States may be necessary except on a question of Adjournment shall be presented to the State having Jurisdiction of any other Emolument from the United States, or in any other Place. Note: Changed by clause 2 of the Seventeenth Day of September in the Year One thousand eight hundred and eight shall in like Manner as if he had signed it, unless the Congress by their Adjournment prevent its Return, in which Case it shall be sent, together with the Vice-President, chosen for the same shall devolve on the Execution of his Office, he shall have Power To lay and collect Taxes, Duties, Imposts and Excises, to pay the Debts and provide for the Case of Removal, Death, Resignation or Inability, both of the United States which may be entitled in the Congress: but no Appropriation of Money to that Use shall be Commander in Chief of the Army and Navy of the President from Office, or Title, of any kind whatever, from any King, Prince, or foreign State. To borrow money on the credit of the State of New Hampshire shall be vacated at the Expiration of the Union, and recommend to their Consideration such Measures as he shall think proper to admit, shall not be a Law.
