#+title: About Me
#+date: 2021-02-22 14:29:29 
#+draft: false
#+layout: single

Hello! I'm Jacob, currently a senior at the University of Mary Washington. I'm part of the class of 2021, majoring in Computer Science and minoring in Cybersecurity. Outside of the classwork I have, I have a deep love of games, both tabletop and video games. If you had to ask me what my favorite video game is, I would have to say Super Metroid, from the SNES. I feel like a lot of it boils down to the individual elements, rather than the game as a whole. 


I also enjoy worldbuilding. My two most recent projects are [[https://jhilker.gitlab.io/brokenThrones/][Broken Thrones]], an alt-history/low fantasy setting, and [[https://jhilker.gitlab.io/shatteredSkies/][Shattered Skies]], a Metroid-meets-Halo-meets-Destiny, gritty sci-fi setting.

Outside of games and worldbuilding, I also develop themes for the static site generator [[https://gohugo.io][Hugo]]. I'm currently working on two at the moment - an all-in-one blog, portfolio, and CV theme, and then a wiki theme.