#+hugo_base_dir: ../
#+hugo_section: ./
#+seq_todo: TODO(t) DRAFT(d) | DONE(D)
* DONE Home
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_LAYOUT: index
:END:
** HELLO WORLD
  Hello there, and welcome to my website. This currently houses my resume (both as a webpage and as a [[/uploads/resume.pdf][PDF]]), as well as some of the projects I’ve been working on. I’m working on a blog currently, but that will be up sometime in the future. This site was written in Emacs’ Org-Mode, using Hugo as a static site generator. This site is using a modified version of the [[https://github.com/lxndrblz/anatole][Anatole]] theme for Hugo, as well as the wrapper from Luis Fuentes' [[https://gitlab.com/luisfuentes/resume/][resume project]] on Gitlab. 

** ABOUT ME
  I graduated from the University of Mary Washington in May 2021, with a Bachelor's of Science in computer science, and a minor in cybersecurity.

  I’ve been a drummer since about 6th grade, and I’ve been teaching myself guitar on and off since sophomore year of high school. Most recently, in January 2021 I started teaching myself bass. As far as my hobbies outside of code and music, I enjoy worldbuilding and games (both video games and tabletop games, especially tabletop role-playing games.) Feel free to explore around.

** FEATURED POSTS
These posts are the ones that I find the most interesting.
{{< featured count="3" >}}

** RECENT POSTS
Interested in some of the things I write on my blog? Check them out here.
{{< recents count="3" >}}

* About Me
:PROPERTIES:
:EXPORT_FILE_NAME: index.md
:export_hugo_bundle: about
:EXPORT_HUGO_LAYOUT: about
:END:
Hello! I'm Jacob, a former student of the University of Mary Washington. I graduated with a major in Computer Science with a minor in cybersecurity.  Although I majored in cybersecurity, I found that it really wasn't what I was looking for - my original plan was to minor in political science, but the closest thing the university had was International Relations, which wasn't exactly what I was looking for - this was also around the time the [[wiki:Facebook%E2%80%93Cambridge_Analytica_data_scandal][Facebook-Cambridge Analytica scandal]] was coming to light, and so I figured that cybersecurity was going to become very quickly involved with political science.


Beyond software, I have a deep love of games, both tabletop and video games. If you had to ask me what my favorite video game is, I would have to say Super Metroid, from the SNES. I feel like a lot of it boils down to the individual elements, rather than the game as a whole. 


I also enjoy worldbuilding. My two most recent projects are [[https://brokenthrones.jhilker.com][Broken Thrones]], an alt-history/low fantasy setting, and [[https://shatteredskies.jhilker.com/][Shattered Skies]], a Metroid-meets-Halo-meets-Destiny, gritty sci-fi setting.

Outside of games and worldbuilding, I also develop themes for the static site generator [[https://gohugo.io][Hugo]]. I'm currently working on two at the moment - [[github:jhilker1/hugo-all-for-one][All For One]], an all-in-one blog, portfolio, and CV theme, as well as a variant of it for wikis, which I am calling [[github:jhilker1/hugo-halfmoon-wiki][Halfmoon Wiki]] until I can come up with a better name for it.


* DRAFT Contact
:PROPERTIES:
:EXPORT_FILE_NAME: contact
:END:
Need to reach out to me? Fill out this form, and I'll get back to you as quickly as I can.
#+begin_export html
<div class="contact">
<form action="https://airform.io/jacob.hilker2@gmail.com" method="post">
  <input type="text" name="name" placeholder="Name">
  <input type="text" name="email" placeholder="Email">
  <br>
  <br>
  <textarea name="message" placeholder="Enter your message."></textarea>
  <br><br>
  <button>Send</button>
</form>
</div>
#+end_export

* Projects
:PROPERTIES:
:EXPORT_HUGO_LAYOUT: portfolio
:export_hugo_section: projects/
:export_file_name: _index
:END:


* Jacob's Blog
:PROPERTIES:
:export_hugo_section: blog
:export_file_name: _index.md
:END:

* Archive
:PROPERTIES:
:export_file_name: _index.md
:export_hugo_section: blog/archive/
:END:
